sudo: false
language: bash
before_install:
  - git lfs pull
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - realpath
    - minimap2
    - nanopolish
    - samtools
    - tabix
script: 
  - bats t/np_basecall-demux_guppy.sh
  - bats t/np_prepSample_readLengths.sh
  - bats t/np_assemble_wtdbg2.sh
  - bats t/np_polish_medaka.sh

