sudo: false
language: bash
before_install:
  - wget -q https://mirror.oxfordnanoportal.com/software/analysis/ont_guppy_2.2.2-1~xenial_amd64.deb
  - dpkg -i --ignore-depends=nvidia-384,libcuda1-384 ont_guppy_2.2.2-2~xenial_amd64.deb
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    #- sourceline: 'deb http://mirror.oxfordnanoportal.com/apt xenial-stable non-free'
    packages:
    - bats
    - realpath
    - minimap2
    - nanopolish
    - samtools
    - tabix
    - ncbi-blast+
    - conda
    - gcc
  homebrew:
    taps: brewsci/bio
    casks:
      - wtdbg2

script: 
  - make
  - make t/np_basecall-demux_guppy.done
  - make t/np_prepSample_readLengths.sh.done
  - make t/np_assemble_wtdbg2.sh.done
  - make t/np_polish_medaka.sh.done

