sudo: false
language: bash
before_install:
  - export PATH=$PATH:$HOME/.local/bin
  - pip install chiron --user
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - realpath
    - minimap2
    - nanopolish
    - samtools
    - tabix
    - ncbi-blast+
  homebrew:
    taps: brewsci/bio
    casks:
      - wtdbg2

script: 
  - make
  - make t/np_basecall-demux_guppy.sh.done
  - make t/np_prepSample_readLengths.sh.done
  - make t/np_assemble_wtdbg2.sh.done
  - make t/np_polish_medaka.sh.done

