sudo: false
language: bash
before_install:
  - git lfs pull
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    - sourceline: 'deb http://mirror.oxfordnanoportal.com/apt xenial-stable non-free'
    packages:
    - bats
    - realpath
    - minimap2
    - nanopolish
    - samtools
    - tabix
    - ncbi-blast+
    - ont-guppy-cpu
  homebrew:
    taps: brewsci/bio
    casks:
      - wtdbg2

script: 
  - bats t/np_basecall-demux_guppy.sh
  - bats t/np_prepSample_readLengths.sh
  - bats t/np_assemble_wtdbg2.sh
  - bats t/np_polish_medaka.sh

